export const IMAGES = {
  cover: require('./cover.webp'),
  coverDark: require('./cover-dark.webp'),
  avatar: require('./avatar.jpeg'),
  totem: require('./totem.webp'),
  t2m: require('./t2m.jpg'),
  faks: require('./faks.webp'),
  milinus: require('./milinus.webp'),
  safetyOlympicsSodexo: require('./safety-olympics-sodexo.jpeg'),
  tamers: require('./tamers.webp'),
  nobelGame: require('./nobel-game.png'),
  design4green: require('./design4green.jpeg'),
  elium: require('./elium.webp'),
  goodbet: require('./goodbet.png'),
}
